vim.keymap.set("i", "<C-S>", "<C-O>:w<CR>")
vim.keymap.set("n", "<C-S>", ":w<CR>")
vim.keymap.set("n", "<Leader>f", ":Telescope current_buffer_fuzzy_find<CR>")
--vim.keymap.set('n', '<C-f>', ':FzfLua lgrep_curbuf<CR>')
vim.keymap.set("n", "<Leader>g", ":Telescope live_grep<CR>")
-- vim.keymap.set('n', '<C-g>', ':FzfLua live_grep_resume<CR>')
vim.keymap.set("n", "<C-p>", ":Telescope find_files hidden=true<CR>")
vim.keymap.set("n", "<Leader><Space>", ":Telescope find_files hidden=true<CR>")
-- vim.keymap.set('n', '<C-p>', ':FzfLua files<CR>')
vim.keymap.set("n", "<Leader>b", ":Telescope buffers<CR>")
vim.keymap.set("n", "<Leader><Leader>", ":Telescope buffers<CR>")
vim.keymap.set("n", "<Leader>p", ":Telescope pickers<CR>")
vim.keymap.set("n", "<Leader>r", ":Telescope resume<CR>")
vim.keymap.set("n", "gd", ":Telescope lsp_definitions<CR>")
vim.keymap.set("n", "gi", ":Telescope lsp_implementations<CR>")
vim.keymap.set("n", "<Leader>t", ":Trouble diagnostics toggle filter.buf=0<CR>")
vim.keymap.set("n", "<Leader><Tab>", ":Neotree toggle<CR>")
vim.keymap.set("n", "<Leader><Left>", "<C-w><Left>")
vim.keymap.set("n", "<Leader><Right>", "<C-w><Right>")
vim.keymap.set("n", "<Leader><Up>", "<C-w><Up>")
vim.keymap.set("n", "<Leader><Down>", "<C-w><Down>")
--Using instead the barbar.nvim bindings
vim.keymap.set("n", "th", " :tabfirst<CR>")
vim.keymap.set("n", "tj", " :tabprev<CR>")
vim.keymap.set("n", "tk", " :tabnext<CR>")
vim.keymap.set("n", "tl", " :tablast<CR>")
vim.keymap.set("n", "tt", " :tabedit<Space>")
vim.keymap.set("n", "tn", " :tabnew<Space>")
vim.keymap.set("n", "tm", " :tabm<Space>")
vim.keymap.set("n", "td", " :tabclose<CR>")
vim.keymap.set({ "n", "x", "o" }, "s", "<Plug>(leap)")
-- map('n', 'th', ' :BufferGoto 1<CR>')
-- map('n', 'tj', ' :BufferPrevious<CR>')
-- map('n', 'tk', ' :BufferNext<CR>')
-- map('n', 'tl', ' :BufferLast<CR>')
-- map('n', 'td', ' :BufferClose<CR>')
