require("lua.env")
require("lua.nvidia")
require("lua.monitors")
require("lua.startup")
require("lua.input")
require("lua.general")
require("lua.misc")
require("lua.decoration")
-- require("lua.animations")
require("lua.layouts.dwindle")
require("lua.gestures")
-- require("lua.plugins")
require("lua.bindings")
require("lua.rules")
