hl.on("hyprland.start", function()
  hl.exec_cmd("hyprpm reload")
  hl.exec_cmd("vicinae server")
  hl.exec_cmd("dunst")
  -- hl.exec_cmd("ags run")
  hl.exec_cmd("waybar -c ~/.config/waybar/config-hyprland")
  hl.exec_cmd("swayosd-server")
  hl.exec_cmd("pypr")
  hl.exec_cmd("lxpolkit")
  hl.exec_cmd("gammastep-indicator")
  hl.exec_cmd("nextcloud & dropbox")
  -- hl.exec_cmd("waypaper-engine")
  -- hl.exec_cmd("swww img ~/.config/wallpapers/lake-and-mountains-nature.webp")
  hl.exec_cmd("blueman-applet & nm-applet & solaar --window=hide")
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("hypridle")
end)
