# More option see https://github.com/DreamMaoMao/mango/wiki/
source=./startup.conf
source=./effects.conf
source=./layout.conf
source=./input.conf
source=./bindings.conf
source=./rules.conf
source=./appearance.conf
source=./misc.conf
source=./overview.conf
