#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

# Install ZSH
#sudo apt install -y zsh curl git

# Install oh-my-zsh
rm -rf ~/.oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

CUSTOMDIR=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}

echo "Init submodules"
yadm submodule update --recursive --init

# Make ZSH the default shell
chsh -s $(which zsh)
