#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

# Install ZSH
#sudo apt install -y zsh curl git
WHICH_ZSH=$(which zsh 2> /dev/null)

if [[ ! -n $WHICH_ZSH ]]; then
  WHICH_APT=$(which apt 2> /dev/null)

  if [[ -n $WHICH_APT ]]; then
    sudo apt install -y zsh curl git
  else
    WHICH_PACMAN=$(which pacman 2> /dev/null)

    if [[ -n $WHICH_PACMAN ]]; then
      sudo pacman -Syu zsh curl git
    else
      echo "NO SUPPORTED PACKAGE MANAGER FOUND"
      exit 1
    fi
  fi
fi

# Install oh-my-zsh
rm -rf ~/.oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

CUSTOMDIR=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}

echo "Init submodules"
yadm submodule update --recursive --init

# Make stuff with the submodules
cp ~/.config/rofi/themes/rofi-themes/themes/* ~/.config/rofi/themes

# Make ZSH the default shell
chsh -s $WHICH_ZSH
