# Nvidia specific config
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
# env = GBM_BACKEND,nvidia-drm
env = NVD_BACKEND,direct
# Electron
env = ELECTRON_OZONE_PLATFORM_HINT,auto
