directory: /mnt/disk_media/media/Musica/MP3
import:
  languages: en es
  move: false
  log: ~/.config/beets/log.txt
ui:
  color: yes
paths:
  default: $albumartist/$original_year - $album%aunique{}/$track - $title
  comp: $albumartist/Compilations/$original_year - $album%aunique{}/$track - $title
  singleton: $artist - $title
  #albumtype:soundtrack: Bandas Sonoras/$album/$track - $title
  albumtype:single: $albumartist/Singles/$original_year - $album%aunique{}/$track - $title
  albumtype:ep: $albumartist/EPs/$original_year - $album%aunique{}/$track - $title
plugins: info convert musicbrainz
convert:
  format: mp3
  formats:
    mp3:
      command: lame --preset insane --noreplaygain $source $dest
      extension: mp3
