[theme]
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

[theme.templates]
enable_builtin_templates = true
builtin_ids = [
  "mango",
  "gtk3",
  "gtk4",
  "qt",
  "kitty",
  "opencode",
  "feishin",
  "neovim",
  "obsidian",
  "prismlauncher",
  "steam",
  "obs",
  "lazygit"
]
